name: GitHub4Womenx Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '3.1.x'

    - name: Update .NET SDK
      run: |
        sudo apt update
        sudo apt install dotnet-sdk-5.0  # Instalação do SDK 5.0

    - name: Execute build
      run: |
        chmod +x ./build.sh
        ./build.sh